words = {
    "PL": [
        "dom", "las", "kot", "pies", "most", "auto", "rower", "klucz", "wazon", "torba",
        "pokoj", "zamek", "okno", "korek", "balon", "praca", "jablko", "kawa", "pudelko", "projekt",
        "kanapa", "pilot", "lampa", "dzwon", "kredyt", "papier", "wiatr", "talerz", "tkanin", "podusz",
        "zegarek", "galaz", "narzed", "linia", "mostek", "smycz", "obraz", "kwiate", "poklon", "ksiazka",
        "pomiar", "kubek", "garnek", "kuchen", "gazeta", "cisza", "lampka", "gwiazda", "drzwi", "szklak",
        "cieplo", "kubik", "koszyk", "sciany", "myszka", "lodyga", "kartka", "drzewo", "lodowk", "krzesl",
        "czapka", "piesek", "lisek", "zamecz", "nocnik", "karmel", "kurtka", "taksow", "balony", "ramka",
        "kolory", "plakat", "zwierz", "pieczk", "lyzecz", "widocz", "sklepik", "budzik", "akapit", "butelka",
        "stojak", "dzialka", "poplyn", "zabaw", "chorob", "przepis", "litera", "szufla", "skok", "lodka",
        "pianka", "wiosna", "szybka", "lazienk", "sliczn", "okulary", "ogrod", "kredki", "stojac", "fotelik",
        "donicz", "okrag", "zegar", "plecak", "bankow", "masecz", "brat", "ziemia", "kasyno", "szalik",
        "kwiat", "krata", "czwar", "dziki", "zwir", "krawat", "konew", "bialy", "samoch", "pudel", "sklep",
        "karte", "taniec", "kompas", "poklon", "gorycz", "talerz", "szal", "kredy", "drapak", "trawa",
        "cichy", "lampki", "glosy", "podroz", "burza", "rekiny", "lodki", "sprawa", "stoper", "drzewka",
        "siedz", "swiat", "robale", "widok", "rzeka", "okrywka", "wiadomo", "spotka", "sufit", "smiech",
        "zamyka", "snieg", "koty", "gryzon", "poslan", "lizaki", "wzgorz", "zdjec", "zajaca", "sklepic",
        "oddech", "deszcz", "ramki", "spokoj", "garaze", "plan", "motor", "kamera", "lizaka", "rozwoj",
        "obecna", "promyk", "zakupy", "obiekt", "plaskie", "zolwik", "radosn", "dlugi", "powrot", "piec",
        "karton", "szlak", "bratki", "medal", "zwierze", "prosta", "rozeta", "tulipan", "kresek", "obcas",
        "mikrol", "odkryc", "rzutnik", "serwet", "zloty", "stacja", "obecn", "pytaj", "wyglad", "tesknot"
    ],
    "EN": [
        "apple", "bridge", "cat", "forest", "market", "orange", "school", "flower", "dog", "summer",
        "rabbit", "island", "castle", "shadow", "button", "stream", "silver", "hunter", "anchor", "coffee",
        "dragon", "garden", "circle", "rocket", "cactus", "pepper", "helmet", "ticket", "winter", "bucket",
        "pillow", "ladder", "desert", "cotton", "planet", "bottle", "camera", "velvet", "guitar", "pirate",
        "puppet", "street", "beacon", "hammer", "tunnel", "animal", "rescue", "marble", "jungle", "tablet",
        "butter", "shrimp", "cloud", "lamp", "spring", "rock", "jacket", "pencil", "anchor", "flask",
        "storm", "trace", "chair", "glass", "mirror", "tower", "smile", "magic", "movie", "river",
        "dream", "track", "train", "stone", "house", "shirt", "cliff", "power", "piano", "bread", "whale",
        "mouse", "space", "shade", "cream", "phone", "brick", "chain", "music", "beach", "field", "party",
        "ocean", "plane", "dance", "guard", "flock", "voice", "queen", "spice", "shelf", "radio", "truth",
        "grape", "shine", "flute", "pride", "level", "angel", "trail", "sword", "crust", "peace", "sharp",
        "broom", "grain", "steel", "stone", "swing", "table", "maple", "plant", "earth", "clock", "brush",
        "glory", "heart", "mango", "watch", "grace", "water", "chase", "punch", "model", "cable", "spine",
        "cloud", "sweet", "mouse", "chart", "pilot", "trail", "price", "hatch", "fleet", "crash", "pulse",
        "glass", "hover", "swift", "orbit", "stack", "drone", "proud", "quilt", "split", "brave", "blush",
        "graph", "spoil", "brain", "witty", "gloom", "tough", "amber", "chaos", "torch", "chill", "quake",
        "punch", "valve", "heist", "shiny", "tasty", "fuzzy", "lemon", "prank", "hover", "noble", "climb"
    ]
}
